// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Hunger_Guru.Model;
//
//    var restaurantDetails = RestaurantDetails.FromJson(jsonString);

namespace Hunger_Guru.Models
{
    using System;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RestaurantDetails
    {
        [JsonProperty("R")]
        public Res_R R { get; set; }

        [JsonProperty("apikey")]
        public string Apikey { get; set; }

        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("location")]
        public Res_Location Location { get; set; }

        [JsonProperty("switch_to_order_menu")]
        public long SwitchToOrderMenu { get; set; }

        [JsonProperty("cuisines")]
        public string Cuisines { get; set; }

        [JsonProperty("timings")]
        public string Timings { get; set; }

        [JsonProperty("average_cost_for_two")]
        public long AverageCostForTwo { get; set; }

        [JsonProperty("price_range")]
        public long PriceRange { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("highlights")]
        public string[] Highlights { get; set; }

        [JsonProperty("offers")]
        public object[] Offers { get; set; }

        [JsonProperty("opentable_support")]
        public long OpentableSupport { get; set; }

        [JsonProperty("is_zomato_book_res")]
        public long IsZomatoBookRes { get; set; }

        [JsonProperty("mezzo_provider")]
        public string MezzoProvider { get; set; }

        [JsonProperty("is_book_form_web_view")]
        public long IsBookFormWebView { get; set; }

        [JsonProperty("book_form_web_view_url")]
        public string BookFormWebViewUrl { get; set; }

        [JsonProperty("book_again_url")]
        public string BookAgainUrl { get; set; }

        [JsonProperty("thumb")]
        public string Thumb { get; set; }

        [JsonProperty("user_rating")]
        public RestaurantUserRating UserRating { get; set; }

        [JsonProperty("all_reviews_count")]
        public long AllReviewsCount { get; set; }

        [JsonProperty("photos_url")]
        public Uri PhotosUrl { get; set; }

        [JsonProperty("photo_count")]
        public long PhotoCount { get; set; }

        [JsonProperty("menu_url")]
        public Uri MenuUrl { get; set; }

        [JsonProperty("featured_image")]
        public string FeaturedImage { get; set; }

        [JsonProperty("has_online_delivery")]
        public long HasOnlineDelivery { get; set; }

        [JsonProperty("is_delivering_now")]
        public long IsDeliveringNow { get; set; }

        [JsonProperty("store_type")]
        public string StoreType { get; set; }

        [JsonProperty("include_bogo_offers")]
        public bool IncludeBogoOffers { get; set; }

        [JsonProperty("deeplink")]
        public string Deeplink { get; set; }

        [JsonProperty("is_table_reservation_supported")]
        public long IsTableReservationSupported { get; set; }

        [JsonProperty("has_table_booking")]
        public long HasTableBooking { get; set; }

        [JsonProperty("events_url")]
        public Uri EventsUrl { get; set; }

        [JsonProperty("phone_numbers")]
        public string PhoneNumbers { get; set; }

        [JsonProperty("all_reviews")]
        public R_AllReviews AllReviews { get; set; }

        [JsonProperty("establishment")]
        public object[] Establishment { get; set; }
    }

    public partial class R_AllReviews
    {
        [JsonProperty("reviews")]
        public R_Review[] allReviews { get; set; }
    }

    public partial class R_Review
    {
        [JsonProperty("review")]
        public object[] rest_ReviewReview { get; set; }
    }

    public partial class Res_Location
    {
        [JsonProperty("address")]
        public string R_Address { get; set; }

        [JsonProperty("locality")]
        public string R_Locality { get; set; }

        [JsonProperty("city")]
        public string R_City { get; set; }

        [JsonProperty("city_id")]
        public long R_CityId { get; set; }

        [JsonProperty("latitude")]
        public string R_Latitude { get; set; }

        [JsonProperty("longitude")]
        public string R_Longitude { get; set; }

        [JsonProperty("zipcode")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long R_Zipcode { get; set; }

        [JsonProperty("country_id")]
        public long R_CountryId { get; set; }

        [JsonProperty("locality_verbose")]
        public string R_LocalityVerbose { get; set; }
    }

    public partial class Res_R
    {
        [JsonProperty("has_menu_status")]
        public MenuStatus R_HasMenuStatus { get; set; }

        [JsonProperty("res_id")]
        public long Res_Id { get; set; }

        [JsonProperty("is_grocery_store")]
        public bool ResIsGroceryStore { get; set; }
    }

    public partial class MenuStatus
    {
        [JsonProperty("delivery")]
        public long R_Delivery { get; set; }

        [JsonProperty("takeaway")]
        public long R_Takeaway { get; set; }
    }

    public partial class RestaurantUserRating
    {
        [JsonProperty("aggregate_rating")]
        public string R_AggregateRating { get; set; }

        [JsonProperty("rating_text")]
        public string R_RatingText { get; set; }

        [JsonProperty("rating_color")]
        public string R_RatingColor { get; set; }

        [JsonProperty("rating_obj")]
        public RestaurantRatingObj R_RatingObj { get; set; }

        [JsonProperty("votes")]
        public long R_Votes { get; set; }
    }

    public partial class RestaurantRatingObj
    {
        [JsonProperty("title")]
        public R_Title R_Title { get; set; }

        [JsonProperty("bg_color")]
        public R_BgColor R_BgColor { get; set; }
    }

    public partial class R_BgColor
    {
        [JsonProperty("type")]
        public string R_Type { get; set; }

        [JsonProperty("tint")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long R_Tint { get; set; }
    }

    public partial class R_Title
    {
        [JsonProperty("text")]
        public string R_Text { get; set; }
    }

    public partial class RestaurantDetails
    {
        public static RestaurantDetails FromJson(string json) => JsonConvert.DeserializeObject<RestaurantDetails>(json, Hunger_Guru.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this RestaurantDetails self) => JsonConvert.SerializeObject(self, Hunger_Guru.Models.Converter.Settings);
    }

    

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}

